title: Admazzola's Software
# email:
description:

baseurl: ""
url: "http://admazzola.github.io"
# twitter_username:
github_username: admazzola

# Build settings
markdown: kramdown
highlighter: rouge
