auto: true
title: Admazzola's Upgraded Github Repo Pages
# email:
description: >
  
baseurl: ""
url: "http://admazzola.github.io"
# twitter_username:
github_username: admazzola

# Build settings
markdown: kramdown
highlighter: pygments
