auto: true
title: Admazzola's Projects
# email:
description: >
  Andrew's thoughts on coding, software engineering, and stuff you don't care about.
baseurl: ""
url: "http://admazzola.github.io"
# twitter_username:
github_username: admazzola

# Build settings
markdown: kramdown
highlighter: pygments
